apiVersion: v1

kind: Service

metadata:

  name: bug-prison


spec:

  type: {{ .Values.service.type }}

  selector:

    app: bug-prison


  ports:

  - port: {{ .Values.service.port }}

    targetPort: 80